# IndusJS Fleet iOS Podfile
# Firebase Crashlytics integration for crash reporting
#
# The `Pods/` directory is gitignored. Before the first Xcode build (or after
# pulling Podfile / Podfile.lock changes), run either:
#   (repo root)  ./gradlew iosPodInstall
#   (this folder) ./bootstrap-ios.sh
#   (this folder) pod install

platform :ios, '14.0'
use_frameworks!
inhibit_all_warnings!

target 'iosApp' do
  # Firebase SDK
  pod 'FirebaseCore', '~> 11.6'
  pod 'FirebaseCrashlytics', '~> 11.6'
  pod 'FirebaseAnalytics', '~> 11.6'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'

      # Suppress warnings
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
    end
  end
end

